import "./globals.css";

import { FirebaseProvider } from "./context/FirebaseContext";
import type { Metadata } from "next";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <FirebaseProvider>
        <body>
          <main className="h-screen">
            <Navbar />
            <div className="h-[94%] px-32">{children}</div>
          </main>
        </body>
      </FirebaseProvider>
    </html>
  );
}
